### PR TITLE
increase the amount of idiomatic go

### PR DESCRIPTION
**Pull request by tmc**
Refs #35

### CODE REVIEW

**Comment by okayzed** [comment]
cool! i'll finish reviewing and accept in the AM - looks like it passed all tests and some query commands i ran. 

what was your regex/script for the changes?  my guess is you used codemod/fastmod, but i'm curious how you ignored the under_case inside strings.

**Comment by tmc** [comment]
This was a set of vim macros. I could share them but they’re kind of
gibberish.

**Comment by tmc** [comment]
Basically for a class of linter error I would write a macro that would
address that and run it over the set of lint errors in that class.

By the way I’m totally happy/fine/supportive of you rewriting this change
to set authorship back to the previous line’s author.

**Comment by okayzed** [comment]
:lgtm:

seems like it will be a bit of work for me to take over the authorship of the lines, so i'll just leave as is. took long enough to read through the changes, anyways. 

for testing:

* i tested that remote sybil queries work between this and old version (remote machine has old version of sybil, local machine has new version) using msybil in snorkel repo. 
* i tested that snorkel works with the updated sybil (and exercised normal query paths: time series, tables, samples)
* i ran "make test" and made sure all alternative builds of sybil built properly (note to self: remove unused builds from Makefile)
* i manually tested "inspect"
* did not test 'rebuild' or 'trim' commands yet.

**Pull request merged**
