### PR TITLE
Pkging

### PR DESCRIPTION
**Pull request by seiflotfy**
[lib/common] move common files into common pkg

---
This change is [Reviewable](https://reviewable.io/reviews/logv/sybil/12)

### CODE REVIEW

**Comment by okayzed** [comment]
looks good, nice work! 

likely does not compile as is

---

Review status: 0 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cmd/cmd_digest.go, line 24 at r1](https://reviewable.io:443/reviews/logv/sybil/12#-KwgY7p036WVKIf8LRce:-KwgY7p036WVKIf8LRcf:byf1l52) ([raw file](https://github.com/logv/sybil/blob/9c3c475dfb34e5e588cbe1ee9b1e149daf957c20/src/cmd/cmd_digest.go#L24)):*
> ```Go
> 	t := sybil.GetTable(*sybil.FLAGS.TABLE)
> 	if t.LoadTableInfo() == false {
> 		sybil.common.Warn("Couldn't read table info, exiting early")
> ```

private variable access

---

*[src/cmd/cmd_query.go, line 21 at r1](https://reviewable.io:443/reviews/logv/sybil/12#-KwgYC0cTlYN1Thbrgrc:-KwgYC0cTlYN1Thbrgrd:b8lam79) ([raw file](https://github.com/logv/sybil/blob/9c3c475dfb34e5e588cbe1ee9b1e149daf957c20/src/cmd/cmd_query.go#L21)):*
> ```Go
> 
> 	sybil.FLAGS.PRINT_INFO = flag.Bool("info", false, "Print table info")
> 	sybil.FLAGS.SORT = flag.String("sort", sybil.common.OPTS.SORT_COUNT, "Int Column to sort by")
> ```

is it sybil.common.FLAGS? is that gonna have to be everywhere?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12#-:-KwgY0Rpx-kGPf05ANaS:ba68eci)*

**Comment by okayzed** [comment]
needs resolution of common.FLAGS -> config.FLAGS and common.OPTS -> config.OPTS, otherwise looks good

**Comment by okayzed** [comment]
Reviewed 6 of 59 files at r1, 4 of 11 files at r2, 23 of 49 files at r4.
Review status: 26 of 53 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/cmd/cmd_flags.go, line 5 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlAxnKNpowcabU9nRY:-KwlAxnLXa1p67nMbM6Y:b-pwwuan) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/cmd/cmd_flags.go#L5)):*
> ```Go
> var (
> 	FALSE = false
>  TRUE = true
> ```

weird formatting here? (on reviewable, i see spaces messed up)

---

*[src/lib/config/flags.go, line 167 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlF9p8yC2fHc7lOAHD:-KwlF9p8yC2fHc7lOAHE:bw03ncz) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/lib/config/flags.go#L167)):*
> ```Go
> 	}
> 
> 	// TODO: enable again
> ```

need to enable again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12)*

**Comment by seiflotfy** [comment]
*[src/cmd/cmd_flags.go, line 5 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlAxnKNpowcabU9nRY:-KwlPDRN82XpSJlqU2if:bs7wumb) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/cmd/cmd_flags.go#L5)):*
<details><summary><i>Previously, okayzed (okay) wrote…</i></summary><blockquote>

weird formatting here? (on reviewable, i see spaces messed up)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12)*

**Comment by seiflotfy** [comment]
*[src/lib/config/flags.go, line 167 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlF9p8yC2fHc7lOAHD:-KwlNJiTXLD6NToLL5ae:b-wkoe0s) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/lib/config/flags.go#L167)):*
<details><summary><i>Previously, okayzed (okay) wrote…</i></summary><blockquote>

need to enable again
</blockquote></details>

Can't enable for now, luajit part is messed up a bit. I can try but its cyclic references across packages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12)*

**Comment by seiflotfy** [comment]
*[src/cmd/cmd_flags.go, line 5 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlAxnKNpowcabU9nRY:-KwlRmS8J4YV2pEyIaV8:b-896fix) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/cmd/cmd_flags.go#L5)):*
<details><summary><i>Previously, seiflotfy (Seif Lotfy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12)*

**Comment by okayzed** [comment]
Reviewed 9 of 59 files at r1, 26 of 49 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/lib/config/flags.go, line 167 at r4](https://reviewable.io:443/reviews/logv/sybil/12#-KwlF9p8yC2fHc7lOAHD:-KwlaH9ljD2Ai6hcw_lo:b-d26kl0) ([raw file](https://github.com/logv/sybil/blob/3a605160b5f1cb43853c14704f3353f9edf41a3d/src/lib/config/flags.go#L167)):*
<details><summary><i>Previously, seiflotfy (Seif Lotfy) wrote…</i></summary><blockquote>

Can't enable for now, luajit part is messed up a bit. I can try but its cyclic references across packages
</blockquote></details>

https://github.com/logv/sybil/issues/21

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/logv/sybil/12)*

**Pull request merged**
